# Generated by Django 5.1.3 on 2024-11-27 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_Usuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='clave',
        ),
    ]
