name: CI Pipeline Local with Docker

on:
  push:
    branches:
      - develop

env:
  LOCAL_SONARQUBE_URL: http://localhost:9000 # URL local de SonarQube

jobs:
  local-analysis:
    name: Local Analysis with Docker SonarQube
    runs-on: ubuntu-latest

    steps:
    # 1. Iniciar contenedor Docker de SonarQube
    - name: Start SonarQube Docker Container
      run: |
        docker run -d --name sonarqube -p 9000:9000 sonarqube:latest

    # 2. Esperar a que SonarQube esté listo
    - name: Wait for SonarQube to be Ready
      run: |
        for i in {1..30}; do
          if curl -s ${{ env.LOCAL_SONARQUBE_URL }} >/dev/null; then
            echo "SonarQube is up!"
            break
          fi
          echo "Waiting for SonarQube..."
          sleep 10
        done

    # 3. Checkout del código
    - name: Checkout code
      uses: actions/checkout@v3

    # 4. Construir imagen Docker del backend
    - name: Build Backend Docker Image
      run: |
        cd lab14
        docker build -t backend-app:latest .

    # 5. Construir imagen Docker del frontend
    - name: Build Frontend Docker Image
      run: |
        cd client
        docker build -t frontend-app:latest .

    # 6. Ejecutar contenedor del backend
    - name: Run Backend Container
      run: |
        docker run -d --name backend-container backend-app:latest

    # 7. Ejecutar contenedor del frontend
    - name: Run Frontend Container
      run: |
        docker run -d --name frontend-container frontend-app:latest

    # 8. Ejecutar pruebas del backend dentro del contenedor
    - name: Run Backend Tests in Container
      run: |
        docker exec backend-container python manage.py test

    # 9. Ejecutar pruebas del frontend dentro del contenedor (si aplica)
    - name: Run Frontend Tests in Container
      run: |
        docker exec frontend-container npm test

    # 10. Análisis de SonarQube para backend
    - name: SonarQube Analysis for Backend
      uses: sonarsource/sonarqube-scan-action@v1
      with:
        projectBaseDir: lab14
      env:
        SONAR_HOST_URL: ${{ env.LOCAL_SONARQUBE_URL }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

    # 11. Análisis de SonarQube para frontend
    - name: SonarQube Analysis for Frontend
      uses: sonarsource/sonarqube-scan-action@v1
      with:
        projectBaseDir: client
      env:
        SONAR_HOST_URL: ${{ env.LOCAL_SONARQUBE_URL }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

    # 12. Detener y eliminar los contenedores
    - name: Stop and Remove Containers
      run: |
        docker stop backend-container frontend-container sonarqube
        docker rm backend-container frontend-container sonarqube

    # 13. Eliminar las imágenes Docker
    - name: Remove Docker Images
      run: |
        docker rmi backend-app:latest frontend-app:latest
