name: CI Pipeline

on:
  push:
    branches:
      - main
      - develop

jobs:
  analysis:
    name: CI Pipeline
    runs-on: ubuntu-latest  # Utiliza los runners de GitHub Actions

    steps:
      # 1. Checkout del código
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Configurar Python (para Django)
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12.6'  # Ajusta la versión según tus necesidades

      # 3. Instalar dependencias del backend (Django)
      - name: Install Backend Dependencies
        run: |
          cd lab14
          pip install -r requirements.txt

      # 4. Ejecutar migraciones
      - name: Run Migrations
        run: |
          cd lab14
          python manage.py migrate

      # 5. Ejecutar pruebas del backend
      - name: Run Backend Tests
        run: |
          cd lab14
          

      # 6. Configurar Node.js (para el frontend)
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'  # Ajusta la versión según tus necesidades

      # 7. Instalar dependencias del frontend
      - name: Install Frontend Dependencies
        run: |
          cd client
          npm install

      # 8. Construir el frontend
      - name: Build Frontend
        run: |
          cd client
          npm run build

      # 9. Ejecutar pruebas del frontend (si las tienes)
      - name: Run Frontend Tests
        run: |
          cd client
          npm run build
